---
- hosts: all
  become: yes
  vars:
    ansible_ssh_user: root
    ansible_ssh_pass: electric dancy pants
  roles:
    - role: create_newuser
    - role: install_packages
    - role: set_dns   
    - role: install_keys



