---
- hosts: all
  become: yes
  vars:
    ansible_ssh_user: manager
    ansible_become_user: root
    ansible_become_pass: electric dancy pants
  roles:
    - role: drop_ports
    - role: open_portsall
   

