---
- name: Install some network debugging
  package:
    name: "{{ item }}"
    state: latest
  tags: packages
  with_items:
    - 'tcpdump'
    - 'mtr'
    - 'nano'  
    - 'python-dbus' 
- name: Install network manager (Debian)
  package:
    name: network-manager
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'apt'
- name: Install glib network manager (Debian)
  package:
    name: libnm-glib-dev
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'apt'
- name: Install DNS utilities (Debian)
  package:
    name: dnsutils
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'apt'
- name: Install DNS utilities (CentOS)
  package:
    name: NetworkManager-glib
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'yum'
